version: '3.8'
services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
      target: development-image
    environment:
    - DATABASE_URL=${DATABASE_URL}
    ports:
    - "8000:8000"
    volumes:
      - ..:/application_root
